name: Actualizar README con commits

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Generar historial de commits
        run: git log --oneline -n 20 > README.md

      - name: Commit de cambios
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Actualización automática del README con historial de commits"
          git push
